server:
  port: 9508
spring:
  servlet:
    multipart:
      max-file-size: 20971520
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/h2-database/typora
    username: dev
    password: dev
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-admin-password: dev
        trace: true
        web-allow-others: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
  mapper-locations: classpath:/Mapper/**/*Mapper.xml
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
      id-type: auto
typora:
  upload:
    service:
      previewPath: http://127.0.0.1:9508/api/preview/